feat: add meta morpho vault cap automator
marsfoundation/spark-automations pull request #8
Opened 2024-05-29 16:53 UTC by barrutko

2024-05-29 17:41 UTC, lucas-manuel requested changes

2024-05-29 17:41 UTC, lucas-manuel commented on test/web3-functions/mainnet/meta-morpho.test.ts
> +    it('no pending caps (waiting for the timelock)', async () => {
Boundary condition with timelock needed

2024-05-29 21:35 UTC, barrutko commented on test/web3-functions/mainnet/meta-morpho.test.ts
> +    it('no pending caps (waiting for the timelock)', async () => {
Updated

2024-05-30 11:40 UTC, lucas-manuel approved these changes

2024-06-03 10:04 UTC, merged